name = "narra"
type = "module"
main = ".output/server/index.mjs"
compatibility_date = "2025-08-06"
compatibility_flags = ["nodejs_compat"]

route = "staging-narra.oldhat.xyz/*"
zone_id = "0ae3769923b6304486d22d7449ee855c"

account_id = "947b30f9bcd09ea8c85d7a96918a56c3"